id = "omnetpp-treesitter-msg"
name = "OMNeT++ MSG extension"
version = "0.0.1"
schema_version = 1
authors = ["Gyorgy Szaszko <adam.szaszko@gmail.com>"]
description = "Highlight MSG files with Tree-sitter"
repository = "https://github.com/adamgeoge309/omnetpp-msg-zed"

[grammars.msg]
repository = "https://github.com/omnetpp/tree-sitter-msg"
commit = "4b0b2a657ba40837fb5a84a066290842c9a5a2b8"
